### ISSUE TITLE
Roundabout rendering

### ISSUE THREAD

**Issue by mikelortega** [gravitystorm/OpenCycleMap-Mapping-Guide#2]
Hi! I don't know if this is the place to mention issues about OpenCycleMap.
Many roundabouts are missing and I cannot find out why.
For example:
http://opencyclemap.org/?zoom=17&lat=42.80962&lon=-1.6252&layers=B0000
![image](https://user-images.githubusercontent.com/3043173/80592244-687f1680-8a1f-11ea-96e3-3d4255c87137.png)

**Comment by gravitystorm** [comment]
The best place to report problems with OpenCycleMap or other Thunderforest maps is by email to support@thunderforest.com

However, thanks for this bug report! I've fixed the code bug that caused this, but it requires a full database reload and therefore will take a few days until you see the changes.
